### ISSUE TITLE
Install-Error with PDO Adapter

### ISSUE THREAD

**Issue by solverat** [dpfaffenbauer/pimcore-coreshop#22]
https://github.com/dpfaffenbauer/pimcore-coreshop/blob/87afdae70c6fc42dd163f9a287042df21c759064/lib/CoreShop/Plugin/Install.php#L39

While installing, pimcore throws an error when mysql adapter is not preselected. We need to do fetch the adapter dynamically, like so:

```php
$db = \Pimcore\Resource::get();

if($db->getResource() instanceof \Zend_Db_Adapter_Mysqli) {
			
   return $mysqli->multi_query($sql);
			
} else if ($db->getResource() instanceof \Zend_Db_Adapter_Pdo_Mysql) {

   return $db->getConnection()->exec($sql);

}
```

**Comment by dpfaffenbauer** [comment]
already fixed in branch for version 4.0
