### ISSUE TITLE
Pimcore 4: Tool::convertToCurrency() $toCurrency can be null

### ISSUE THREAD

**Issue by solverat** [dpfaffenbauer/pimcore-coreshop#24]
https://github.com/dpfaffenbauer/pimcore-coreshop/blob/master/lib/CoreShop/Tool.php#L59

```php
public static function convertToCurrency($value, Currency $toCurrency = null, Currency $fromCurrency = null)
```
must called as
```php
public static function convertToCurrency($value, $toCurrency = null, $fromCurrency = null)
```

because ```$toCurrency```and ```$fromCurrency``` can be null. otherwise php wants to initialize with an ```Currency``` instance.

**Comment by dpfaffenbauer** [comment]
59d21a819d
