### ISSUE TITLE
clean up core js file

### ISSUE THREAD

**Issue by solverat** [dpfaffenbauer/pimcore-coreshop#53]
the `shop.js` should be cleaned up and should only provides the core features with custom events triggering.

all default template stuff (like form validation etc) should be inside a template.js, so the user can decide to use it or not.

for an example:
- put shop.js into a class
- only add request events
- trigger custom events within nice namespaces

```js

initEvents : function() {

      $('.btn-cart').on('click', this.addToCart );

},

addToCart : function( ev ) {
       
        $.ajax({
            url : '/de/cart/add',
            data : {product : $(this).data('product-id')},
            dataType: 'json',
            success : function(result,status) {
                if( status == 'success' )

                  if(result.success)  {
            
                    this.updateCart(result.cart);
                    $( document ).trigger( 'coreShop.cart.added.success', [ result ] );

                   } else {

                    $( document ).trigger( 'coreShop.cart.added.error', [ result ] );

                    }

            }

        });

}

````

so user can use all events in a custom environment like so:

```js

$( document ).on( 'coreShop.cart.added', function( event, result ) {

       console.log( result ); // "result from response"

});
 
```

**Comment by dpfaffenbauer** [comment]
i don't think so. 

UI is a template thing, so are this javascript files. if a template doesn't need it, they can delete whatever they want.
