### ISSUE TITLE
specific price improvements

### ISSUE THREAD

**Issue by solverat** [dpfaffenbauer/pimcore-coreshop#58]
the specific price per product is a great thing. maybe we can add some improvments:

#### add specific price tab to edit window next to the "price" tab
<img width="1274" alt="bildschirmfoto 2016-01-30 um 11 14 21" src="https://cloud.githubusercontent.com/assets/700119/12695078/cd72a9c0-c742-11e5-9252-800b387e9078.png">

#### remove old "specific price" in "price" tab 
<img width="772" alt="bildschirmfoto 2016-01-30 um 11 11 36" src="https://cloud.githubusercontent.com/assets/700119/12695070/8164f024-c742-11e5-9011-faf6e051dee2.png">

#### add zones to conditions
let user add zones, which will check the containing countries
<img width="390" alt="bildschirmfoto 2016-01-30 um 11 12 07" src="https://cloud.githubusercontent.com/assets/700119/12695088/068d4396-c743-11e5-9aab-e0e1561f9b18.png">

#### add price to action
let user add a price, which will override the default price
<img width="437" alt="bildschirmfoto 2016-01-30 um 11 11 54" src="https://cloud.githubusercontent.com/assets/700119/12695090/12ec4c90-c743-11e5-9395-79ccccefd67c.png">

**Comment by dpfaffenbauer** [comment]
i dont think its a good idea to move the specific price tab after the price tab. everything inside the edit tab is created dynamically. so it would be possible that someone changes to CoreShopProduct layout and so this feature would be broken,

**Comment by dpfaffenbauer** [comment]
But i implemented the New Price feature and the Zone Condition

**Comment by solverat** [comment]
'remove old "specific price" in "price" tab': is there any reason to keep it?

**Comment by dpfaffenbauer** [comment]
i did remove it with e341001b678c020300fabdd21ea34290eb41cf92
