### ISSUE TITLE
base country / location

### ISSUE THREAD

**Issue by solverat** [dpfaffenbauer/pimcore-coreshop#59]
allow user to set a base country in settings.
- use it for the default fallback in `getCountry();`
- add a hook in `getCountry();` when no country is initial defined ( `if (!$country instanceof Country)`), so a website could override the user country, based on his own geo2ip service or country concept.

**Comment by dpfaffenbauer** [comment]
see #4e32787

Plugin::getEventManager()->attach("actionHook.country", function() {
    return function() {
        return Country::getById(3);
    };
});
